### ISSUE TITLE
Version number in release titles?

### ISSUE THREAD

**Issue by mxmilkiib** [gethiox/HIDI#1]
Hello! I've added HIDI to [libreav.org](https://libreav.org/software/hidi), a site that aggregates release feeds, though when items on https://github.com/gethiox/HIDI/releases are given a title, that is carried through to https://github.com/gethiox/HIDI/releases.atom and overwrites the default version string which makes it impossible to parse the version number from titles. Could I request that the titles be prefixed with the number?

**Comment by gethiox** [comment]
>Hello! I've added HIDI to [libreav.org](https://libreav.org/software/hidi)

Hi, that's pretty cool, thank you!
I've changed it to `v0.1-beta for Raspberry Pi`, is that good enough?

**Comment by mxmilkiib** [comment]
That comes through as 0.1-beta which I guess is cool enough? Thanks!
